# Generated by Django 3.1.3 on 2021-01-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_child_upfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='testres',
            field=models.BooleanField(default=False),
        ),
    ]
