# Generated by Django 3.1.3 on 2021-01-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_files_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_held',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
