# Generated by Django 3.1.3 on 2021-02-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20210131_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='paid', max_length=200),
        ),
    ]
