# Generated by Django 3.1.3 on 2021-03-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20210302_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='availability',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
