# Generated by Django 3.1.3 on 2021-03-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_appointment_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user_prefered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
