# Generated by Django 3.1.3 on 2021-03-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_appointment_user_prefered_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultant_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
