# Generated by Django 3.1.3 on 2021-03-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_appointment_consultant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultant_email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
