# Generated by Django 3.1.3 on 2021-04-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_appointment_consultant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='zoom_join_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='zoom_start_url',
            field=models.TextField(null=True),
        ),
    ]
