# Generated by Django 3.1.3 on 2021-04-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20210401_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user_timezone',
            field=models.CharField(default='Africa/Lagos', max_length=200),
        ),
    ]
