# Generated by Django 3.1.3 on 2021-04-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_appointment_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='timezone',
            field=models.CharField(default='Africa/Lagos', max_length=200),
        ),
    ]
