# Generated by Django 3.1.3 on 2021-04-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_client_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultant_timezone',
            field=models.CharField(default='Africa/Lagos', max_length=200),
        ),
    ]
