# Generated by Django 3.1.3 on 2021-08-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_appointment_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='host_started',
            field=models.BooleanField(default=False),
        ),
    ]
