# Generated by Django 3.1.3 on 2021-08-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_appointment_host_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='guest_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='host_url',
            field=models.URLField(null=True),
        ),
    ]
