export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_ASSIGNMENT_LIST_START = "GET_ASSIGNMENT_LIST_START";
export const GET_ASSIGNMENTS_LIST_FAIL = "GET_ASSIGNMENTS_LIST_FAIL";
export const GET_ASSIGNMENTS_LIST_SUCCESS = "GET_ASSIGNMENTS_LIST_SUCCESS";

export const GET_FORUM_LIST_START = "GET_FORUM_LIST_START";
export const GET_FORUM_LIST_FAIL = "GET_FORUM_LIST_FAIL";
export const GET_FORUM_LIST_SUCCESS = "GET_FORUM_LIST_SUCCESS";

export const GET_COMMENTS_START = "GET_COMMENTS_START";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";

export const POST_COMMENTS_START = "POST_COMMENTS_START";
export const POST_COMMENTS_FAIL = "POST_COMMENTS_FAIL";
export const POST_COMMENTS_SUCCESS = "POST_COMMENTS_SUCCESS";

export const POST_FORUM_START = "POST_FORUM_START";
export const POST_FORUM_FAIL = "POST_FORUM_FAIL";
export const POST_FORUM_SUCCESS = "POST_FORUM_SUCCESS";

export const GET_ASSIGNMENT_DETAIL_START = "GET_ASSIGNMENT_DETAIL_START";
export const GET_ASSIGNMENT_DETAIL_FAIL = "GET_ASSIGNMENT_DETAIL_FAIL";
export const GET_ASSIGNMENT_DETAIL_SUCCESS = "GET_ASSIGNMENT_DETAIL_SUCCESS";

export const CREATE_ASSIGNMENT_START = "CREATE_ASSIGNMENT_START";
export const CREATE_ASSIGNMENT_FAIL = "CREATE_ASSIGNMENT_FAIL";
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";

export const CREATE_RESULT_START = "CREATE_RESULT_START";
export const CREATE_RESULT_FAIL = "CREATE_RESULT_FAIL";
export const CREATE_RESULT_SUCCESS = "CREATE_RESULT_SUCCESS";

export const CREATE_CHILD_START = "CREATE_CHILD_START";
export const CREATE_CHILD_FAIL = "CREATE_CHILD_FAIL";
export const CREATE_CHILD_SUCCESS = "CREATE_CHILD_SUCCESS";

export const GET_CHILDS_START = "GET_CHILDS_START";
export const GET_CHILDS_FAIL = "GET_CHILDS_FAIL";
export const GET_CHILDS_SUCCESS = "GET_CHILDS_SUCCESS";

export const UPDATE_CHILD_START = "UPDATE_CHILD_START";
export const UPDATE_CHILD_SUCCESS= "UPDATE_CHILD_SUCCESS";
export const UPDATE_CHILD_FAIL = "UPDATE_CHILD_FAIL";

export const GET_RESULTS_START = "GET_RESULTS_START";
export const GET_RESULTS_FAIL = "GET_RESULTS_FAIL";
export const GET_RESULTS_SUCCESS = "GET_RESULTS_SUCCESS";

export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
export const ERROR_SUCCESS = "ERROR_SUCCESS";


export const GET_GRADED_ASSIGNMENT_LIST_START =
  "GET_GRADED_ASSIGNMENT_LIST_START";
export const GET_GRADED_ASSIGNMENTS_LIST_FAIL =
  "GET_GRADED_ASSIGNMENTS_LIST_FAIL";
export const GET_GRADED_ASSIGNMENTS_LIST_SUCCESS =
  "GET_GRADED_ASSIGNMENTS_LIST_SUCCESS";

export const CREATE_GRADED_ASSIGNMENT_LIST_START =
  "CREATE_GRADED_ASSIGNMENT_LIST_START";
export const CREATE_GRADED_ASSIGNMENTS_LIST_FAIL =
  "CREATE_GRADED_ASSIGNMENTS_LIST_FAIL";
export const CREATE_GRADED_ASSIGNMENTS_LIST_SUCCESS =
  "CREATE_GRADED_ASSIGNMENTS_LIST_SUCCESS";  