# Generated by Django 3.1.3 on 2021-01-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210122_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_forum', to='forum.forum'),
        ),
    ]
