# Generated by Django 3.1.3 on 2021-01-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20210125_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='forum',
            name='desc',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
